# ============================================================================
# VOCALYX - Architecture Microservices Complète (Version Podman Compose)
# ============================================================================
# Cette configuration est une adaptation 1:1 de `docker-compose.yml`
# pour une utilisation avec Podman / podman-compose.
# 
# Notes :
# - La syntaxe Compose reste la même, Podman est compatible avec le format.
# - Les champs `deploy.resources` peuvent être ignorés ou partiellement
#   pris en compte selon la version de Podman / podman-compose.
# - Les noms de services / réseaux / volumes sont conservés à l'identique.
# ============================================================================

services:
  # ==========================================================================
  # BASE DE DONNÉES - PostgreSQL
  # ==========================================================================
  postgres:
    image: postgres:15-alpine
    container_name: vocalyx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vocalyx_db
      POSTGRES_USER: vocalyx
      POSTGRES_PASSWORD: vocalyx_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vocalyx -d vocalyx_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================================================
  # REDIS - Broker Celery + Cache
  # ==========================================================================
  redis:
    image: redis:7-alpine
    container_name: vocalyx-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================================================
  # HAProxy - Load Balancer et Reverse Proxy
  # ==========================================================================
  haproxy:
    image: haproxy:2.8-alpine
    container_name: vocalyx-haproxy
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8000:8000"      # API REST et WebSocket
      - "8404:8404"      # Stats HAProxy (optionnel)
    depends_on:
      vocalyx-api-01:
        condition: service_healthy
      vocalyx-api-02:
        condition: service_healthy
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "pidof haproxy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ==========================================================================
  # API CENTRALE #1 - vocalyx-api-01
  # ==========================================================================
  vocalyx-api-01:
    build:
      context: ./vocalyx-api
      dockerfile: Containerfile
    container_name: vocalyx-api-01
    restart: unless-stopped
    environment:
      # Database
      DATABASE_URL: postgresql://vocalyx:vocalyx_secret@postgres:5432/vocalyx_db
      
      # Redis & Celery
      REDIS_URL: redis://vocalyx-redis:6379/0
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      
      # Sécurité (⚠️ CHANGER EN PRODUCTION)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      ADMIN_PROJECT_NAME: ISICOMTECH
      
      # CORS (inclure HAProxy et frontend)
      CORS_ORIGINS: http://localhost:8080,http://vocalyx-frontend:8080,http://localhost:8000,http://haproxy:8000

      UPLOAD_DIR: /app/shared_uploads
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "false"
      LOG_FILE_PATH: /app/logs/vocalyx-api-01.log
    volumes:
      - ./shared/uploads:/app/shared_uploads
      - ./shared/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ==========================================================================
  # API CENTRALE #2 - vocalyx-api-02
  # ==========================================================================
  vocalyx-api-02:
    build:
      context: ./vocalyx-api
      dockerfile: Containerfile
    container_name: vocalyx-api-02
    restart: unless-stopped
    environment:
      # Database
      DATABASE_URL: postgresql://vocalyx:vocalyx_secret@postgres:5432/vocalyx_db
      
      # Redis & Celery
      REDIS_URL: redis://vocalyx-redis:6379/0
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      
      # Sécurité (⚠️ CHANGER EN PRODUCTION)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      ADMIN_PROJECT_NAME: ISICOMTECH
      
      # CORS (inclure HAProxy et frontend)
      CORS_ORIGINS: http://localhost:8080,http://vocalyx-frontend:8080,http://localhost:8000,http://haproxy:8000

      UPLOAD_DIR: /app/shared_uploads
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "false"
      LOG_FILE_PATH: /app/logs/vocalyx-api-02.log
    volumes:
      - ./shared/uploads:/app/shared_uploads
      - ./shared/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ==========================================================================
  # FRONTEND - vocalyx-frontend (anciennement dashboard)
  # ==========================================================================
  vocalyx-frontend:
    build:
      context: ./vocalyx-frontend
      dockerfile: Containerfile
    container_name: vocalyx-frontend
    restart: unless-stopped
    environment:
      # API URL - passe par HAProxy pour le load balancing
      VOCALYX_API_URL: http://haproxy:8000
      
      # Sécurité (⚠️ DOIT être identique à vocalyx-api)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      ADMIN_PROJECT_NAME: ISICOMTECH
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "false"
      LOG_FILE_PATH: /app/logs/vocalyx-frontend.log
    volumes:
      - ./shared/logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      haproxy:
        condition: service_started
      vocalyx-api-01:
        condition: service_healthy
      vocalyx-api-02:
        condition: service_healthy
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================================================
  # WORKER TRANSCRIPTION #1 - vocalyx-transcribe
  # ==========================================================================
  vocalyx-transcribe-01:
    build:
      context: ./vocalyx-transcribe
      dockerfile: Containerfile
    container_name: vocalyx-transcribe-01
    restart: unless-stopped
    environment:
      # Instance
      INSTANCE_NAME: worker-01
      
      # API - passe par HAProxy pour le load balancing
      VOCALYX_API_URL: http://haproxy:8000
      
      # Celery
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      
      # Whisper
      WHISPER_MODEL: ./models/transcribe/openai-whisper-small
      WHISPER_DEVICE: cpu
      WHISPER_COMPUTE_TYPE: int8
      WHISPER_LANGUAGE: fr
      
      # Performance
      MAX_WORKERS: 2
      VAD_ENABLED: "true"

      UPLOAD_DIR: /app/shared_uploads
      
      # Sécurité (⚠️ DOIT être identique à vocalyx-api)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "true"
      LOG_FILE_PATH: /app/logs/vocalyx-transcribe-01.log
    volumes:
      - ./shared/uploads:/app/shared_uploads
      - ./shared/models/transcribe:/app/models/transcribe
      - ./shared/logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      haproxy:
        condition: service_started
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "4"
          memory: 4G
    command: >
      celery -A worker.celery_app worker
      --loglevel=info
      --concurrency=2
      --hostname=worker-01@%h
      --without-gossip
      --without-mingle
      -Q transcription

  # ==========================================================================
  # WORKER ENRICHISSEMENT #1 - vocalyx-enrichment
  # ==========================================================================
  vocalyx-enrichment-01:
    build:
      context: ./vocalyx-enrichment
      dockerfile: Containerfile
    container_name: vocalyx-enrichment-01
    restart: unless-stopped
    environment:
      # Instance
      INSTANCE_NAME: enrichment-worker-01
      
      # API - passe par HAProxy pour le load balancing
      VOCALYX_API_URL: http://haproxy:8000
      
      # Celery
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      
      # LLM
      LLM_DEVICE: cpu
      
      # Sécurité (⚠️ DOIT être identique à vocalyx-api)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "true"
      LOG_FILE_PATH: /app/logs/vocalyx-enrichment-01.log
    volumes:
      - ./shared/logs:/app/logs
      - ./shared/models:/app/models
      - ./shared/models/enrichment:/app/models/enrichment
    depends_on:
      redis:
        condition: service_healthy
      haproxy:
        condition: service_started
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "4"
          memory: 2G
    command: >
      celery -A worker.celery_app worker
      --loglevel=info
      --concurrency=2
      --hostname=enrichment-worker-01@%h
      --without-gossip
      --without-mingle
      -Q enrichment

  # ==========================================================================
  # WORKER ENRICHISSEMENT #2 - vocalyx-enrichment
  # ==========================================================================
  vocalyx-enrichment-02:
    build:
      context: ./vocalyx-enrichment
      dockerfile: Containerfile
    container_name: vocalyx-enrichment-02
    restart: unless-stopped
    environment:
      # Instance
      INSTANCE_NAME: enrichment-worker-02
      
      # API - passe par HAProxy pour le load balancing
      VOCALYX_API_URL: http://haproxy:8000
      
      # Celery
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      
      # LLM
      LLM_DEVICE: cpu
      
      # Sécurité (⚠️ DOIT être identique à vocalyx-api)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "true"
      LOG_FILE_PATH: /app/logs/vocalyx-enrichment-02.log
    volumes:
      - ./shared/logs:/app/logs
      - ./shared/models:/app/models
      - ./shared/models/enrichment:/app/models/enrichment
    depends_on:
      redis:
        condition: service_healthy
      haproxy:
        condition: service_started
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "4"
          memory: 2G
    command: >
      celery -A worker.celery_app worker
      --loglevel=info
      --concurrency=2
      --hostname=enrichment-worker-02@%h
      --without-gossip
      --without-mingle
      -Q enrichment

  # ==========================================================================
  # WORKER TRANSCRIPTION #2 - vocalyx-transcribe
  # ==========================================================================
  vocalyx-transcribe-02:
    build:
      context: ./vocalyx-transcribe
      dockerfile: Containerfile
    container_name: vocalyx-transcribe-02
    restart: unless-stopped
    environment:
      # Instance
      INSTANCE_NAME: worker-02
      
      # API - passe par HAProxy pour le load balancing
      VOCALYX_API_URL: http://haproxy:8000
      
      # Celery
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      
      # Whisper
      WHISPER_MODEL: ./models/transcribe/openai-whisper-small
      WHISPER_DEVICE: cpu
      WHISPER_COMPUTE_TYPE: int8
      WHISPER_LANGUAGE: fr
      
      # Performance
      MAX_WORKERS: 2
      VAD_ENABLED: "true"

      UPLOAD_DIR: /app/shared_uploads
      
      # Sécurité (⚠️ DOIT être identique à vocalyx-api)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "true"
      LOG_FILE_PATH: /app/logs/vocalyx-transcribe-02.log
    volumes:
      - ./shared/uploads:/app/shared_uploads
      - ./shared/models/transcribe:/app/models/transcribe
      - ./shared/logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      haproxy:
        condition: service_started
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "4"
          memory: 4G
    command: >
      celery -A worker.celery_app worker
      --loglevel=info
      --concurrency=2
      --hostname=worker-02@%h
      --without-gossip
      --without-mingle
      -Q transcription

  # ==========================================================================
  # WORKER TRANSCRIPTION #3 - vocalyx-transcribe
  # ==========================================================================
  vocalyx-transcribe-03:
    build:
      context: ./vocalyx-transcribe
      dockerfile: Containerfile
    container_name: vocalyx-transcribe-03
    restart: unless-stopped
    environment:
      # Instance
      INSTANCE_NAME: worker-03
      
      # API - passe par HAProxy pour le load balancing
      VOCALYX_API_URL: http://haproxy:8000
      
      # Celery
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      
      # Whisper
      WHISPER_MODEL: ./models/transcribe/openai-whisper-small
      WHISPER_DEVICE: cpu
      WHISPER_COMPUTE_TYPE: int8
      WHISPER_LANGUAGE: fr
      
      # Performance
      MAX_WORKERS: 2
      VAD_ENABLED: "true"

      UPLOAD_DIR: /app/shared_uploads
      
      # Sécurité (⚠️ DOIT être identique à vocalyx-api)
      INTERNAL_API_KEY: secret_key_pour_comms_internes_123456
      
      # Logging
      LOG_LEVEL: INFO
      LOG_COLORED: "true"
      LOG_FILE_PATH: /app/logs/vocalyx-transcribe-03.log
    volumes:
      - ./shared/uploads:/app/shared_uploads
      - ./shared/models/transcribe:/app/models/transcribe
      - ./shared/logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      haproxy:
        condition: service_started
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "4"
          memory: 4G
    command: >
      celery -A worker.celery_app worker
      --loglevel=info
      --concurrency=2
      --hostname=worker-03@%h
      --without-gossip
      --without-mingle
      -Q transcription

  # ==========================================================================
  # MONITORING CELERY - Flower (OPTIONNEL)
  # ==========================================================================
  flower:
    image: mher/flower:2.0
    container_name: vocalyx-flower
    restart: unless-stopped
    environment:
      CELERY_BROKER_URL: redis://vocalyx-redis:6379/0
      CELERY_RESULT_BACKEND: redis://vocalyx-redis:6379/0
      FLOWER_PORT: 5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - vocalyx-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    command: >
      celery --broker=redis://vocalyx-redis:6379/0 flower
      --port=5555


# ============================================================================
# VOLUMES PERSISTANTS
# ============================================================================
volumes:
  postgres_data:
    driver: local
  
  redis_data:
    driver: local

# ============================================================================
# NETWORK
# ============================================================================
networks:
  vocalyx-network:
    driver: bridge
    name: vocalyx-network


